enum DbTemplateType {
  singleTenant,
  multiTenant,
}

class SqlGenerator {
  static String generate({
    required DbTemplateType type,
    required String tableName,
    required String columnsInput, // Expecting format: name:type, name:type
    String? schemaName,
  }) {
    final schema = schemaName != null && schemaName.isNotEmpty ? schemaName : 'public';
    final table = tableName.isNotEmpty ? tableName : 'example_table';
    final columns = _parseColumns(columnsInput);
    
    final buffer = StringBuffer();
    
    buffer.writeln('-- SQL Script Generated by SQL Generator App');
    buffer.writeln('-- Template: ${type == DbTemplateType.singleTenant ? "Single Tenant" : "Multi-Tenant"}');
    buffer.writeln('-- Timestamp: ${DateTime.now().toIso8601String()}');
    buffer.writeln();

    if (type == DbTemplateType.singleTenant) {
      _generateSingleTenant(buffer, schema, table, columns);
    } else {
      _generateMultiTenant(buffer, schema, table, columns);
    }

    return buffer.toString();
  }

  static List<String> _parseColumns(String input) {
    if (input.isEmpty) return ['id SERIAL PRIMARY KEY', 'created_at TIMESTAMP DEFAULT NOW()'];
    
    return input.split('\n').where((line) => line.trim().isNotEmpty).map((line) {
      // Simple cleanup
      return line.trim();
    }).toList();
  }

  static void _generateSingleTenant(StringBuffer buffer, String schema, String table, List<String> columns) {
    buffer.writeln('CREATE SCHEMA IF NOT EXISTS $schema;');
    buffer.writeln();
    buffer.writeln('CREATE TABLE IF NOT EXISTS $schema.$table (');
    
    // Add standard ID if not present (simplified logic)
    if (!columns.any((c) => c.toLowerCase().contains('primary key'))) {
       buffer.writeln('    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,');
    }

    for (int i = 0; i < columns.length; i++) {
      final isLast = i == columns.length - 1;
      buffer.writeln('    ${columns[i]}${isLast ? "" : ","}');
    }
    
    buffer.writeln(');');
    buffer.writeln();
    buffer.writeln('-- Index examples');
    buffer.writeln('CREATE INDEX idx_${table}_created_at ON $schema.$table(created_at);');
  }

  static void _generateMultiTenant(StringBuffer buffer, String schema, String table, List<String> columns) {
    buffer.writeln('CREATE SCHEMA IF NOT EXISTS $schema;');
    buffer.writeln();
    buffer.writeln('CREATE TABLE IF NOT EXISTS $schema.$table (');
    
    // Standard ID
    if (!columns.any((c) => c.toLowerCase().contains('primary key'))) {
       buffer.writeln('    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,');
    }

    // Tenant ID is mandatory for multi-tenant
    buffer.writeln('    tenant_id UUID NOT NULL,'); // Assuming UUID for tenant_id

    for (int i = 0; i < columns.length; i++) {
      buffer.writeln('    ${columns[i]},');
    }
    
    // Remove trailing comma logic handled by just adding standard columns last or carefully
    // For simplicity in this demo, we assume the user inputs valid SQL column defs
    // Let's just close it cleanly.
    buffer.writeln('    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),');
    buffer.writeln('    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()');
    
    buffer.writeln(');');
    buffer.writeln();
    
    buffer.writeln('-- Multi-tenant specific indexes');
    buffer.writeln('CREATE INDEX idx_${table}_tenant_id ON $schema.$table(tenant_id);');
    buffer.writeln();
    
    buffer.writeln('-- Row Level Security (RLS) Policy Example');
    buffer.writeln('ALTER TABLE $schema.$table ENABLE ROW LEVEL SECURITY;');
    buffer.writeln();
    buffer.writeln('CREATE POLICY tenant_isolation_policy ON $schema.$table');
    buffer.writeln('    USING (tenant_id = current_setting(\'app.current_tenant_id\')::uuid);');
  }
}
